---

name: Go

on:
  push:
    branches:
      - master
    tags:
      - v*.*.*
  pull_request:
    branches:
      - master

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16

      - name: Lint
        run: |
          go get -u golang.org/x/lint/golint
          golint -set_exit_status ./...

      - name: Vet
        run: go vet ./... | grep ':' && false || true

      - name: Build
        run: go build -v ./...

  build:
    if: startsWith(github.ref, 'refs/tags/v')
    needs: validate
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - os: darwin
            arch: amd64
            arm: ""
            extension: ""
          - os: linux
            arch: amd64
            arm: ""
            extension: ""
          - os: linux
            arch: arm
            arm: 5
            extension: ""
          - os: linux
            arch: arm
            arm: 6
            extension: ""
          - os: linux
            arch: arm64
            arm: ""
            extension: ""
          - os: windows
            arch: 386
            arm: ""
            extension: .exe
          - os: windows
            arch: amd64
            arm: ""
            extension: .exe
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16

      - name: Get tag name
        id: tag
        run: |
          echo ::set-output name=tag_name::${GITHUB_REF#refs/tags/v}

      - name: Create output directory
        run: |
          mkdir -p /tmp/files

      - name: Build
        run: >
          GOOS="${{ matrix.os }}"
          GOARCH="${{ matrix.arch }}"
          GOARM="${{ matrix.arm }}"
          CGO_ENABLED=0
          go build
            -ldflags='-s -w -X github.com/jtyr/gcapi/pkg/version.Version=${{ steps.tag.outputs.tag_name }}'
            -o /tmp/files/gcapi-cli-${{ steps.tag.outputs.tag_name }}-${{ matrix.os }}-${{ matrix.arch }}${{ matrix.arm }}${{ matrix.extension }}
            ./main.go

      - name: Create checksums file
        run: |
          sha256sum /tmp/files/* | sort -k2 > "gcapi-cli-${{ steps.tag.outputs.tag_name }}-checksums-sha256.txt"

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: /tmp/files/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
